# Generated by Django 3.2.9 on 2022-04-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.BooleanField(default=False),
        ),
    ]
