# Generated by Django 3.2.9 on 2022-04-18 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_event_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='last_name',
        ),
        migrations.AddField(
            model_name='participants',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
