# Generated by Django 3.2.9 on 2022-04-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220419_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
