# Generated by Django 3.2.9 on 2022-04-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20220419_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
