# Generated by Django 3.2.9 on 2022-04-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_participant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
    ]
