# Generated by Django 3.2.9 on 2022-04-25 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Członkowie', to='events.event'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(verbose_name='kkk'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='czlonkowie', to='events.Participant'),
        ),
    ]
