# Generated by Django 3.2.9 on 2022-04-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20220425_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participant',
            new_name='participants',
        ),
    ]
