# Generated by Django 3.2.9 on 2022-04-28 14:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_participant_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
