# Generated by Django 3.2.9 on 2022-05-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_remove_participant_is_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participant_list', to='events.Participant'),
        ),
    ]
