# Generated by Django 3.2.9 on 2022-04-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.CharField(default='Przeczytaj więcej, klikając poniższy link ', max_length=255),
        ),
    ]
