# Generated by Django 3.2.9 on 2022-04-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=models.TextField(default='Przeczytaj więcej, klikając poniższy link ', max_length=255),
        ),
    ]
