# Generated by Django 3.2.9 on 2022-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=models.TextField(max_length=600),
        ),
    ]
